spring.application.name=SSA-02OllamaChat

server.port=8002

#?????????
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3.5:0.8b
spring.ai.ollama.api-key=ollama

spring.main.allow-bean-definition-overriding=true

# Web application type (commented out to enable web server)
# spring.main.web-application-type=none